AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Repo and LB
Parameters:
  EnvironmentName:
    Default: app
    Type: String
  VpcID:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0874101045f6300ac
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0ab164fd7b1affced
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0b4b0515fab05df2b
Resources:
  AWSFactorialRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "factorial-app"
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: factorial-lb
      Subnets:
      - !Ref PublicSubnet1
      - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for loadbalancer to services on ECS
      VpcId: !Ref VpcID
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: aws-factorial
      VpcId: !Ref VpcID
      Protocol: HTTP
      Port: 80
Outputs:
  AWSFactorialArn:
     Value: !GetAtt AWSFactorialRepo.Arn
     Export:
       Name: AWSFactorialArn
  LoadBalancerDNS:
    Description: Domain name for the loadbalancer
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Join [':', [ !Ref EnvironmentName, FactorialDomainName ]]
  LoadBalancerListener:
    Description: loadbalancer listener
    Value: !Ref LoadBalancerListener
    Export:
      Name: !Join [':', [ !Ref EnvironmentName, FactorialLoadBalancerListener ]]
  LoadBalancerSecurityGroup:
    Description: Loadbalancer security group
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: !Join [':', [ !Ref EnvironmentName, FactorialLoadBalancerSecurityGroup ]]
